const getFullMonthAttendence = require(`./resolvers/query/getFullMonthAttendence`),
	getDepartments = require(`./resolvers/query/getDepartments`),
	getAttendence = require(`./resolvers/query/getAttendence`),
	getTeacher = require(`./resolvers/query/getTeacher`),
	getStudent = require(`./resolvers/query/getStudent`),
	getCourses = require(`./resolvers/query/getCourse`),
	getClass = require(`./resolvers/query/getClass`),
	getGist = require(`./resolvers/query/getGist`);

const addAttendenceMany = require(`./resolvers/mutation/addAttendenceMany`),
	updateAttendence = require(`./resolvers/mutation/updateAttendence`),
	addAttendence = require(`./resolvers/mutation/addAttendence`),
	updateStudent = require(`./resolvers/mutation/updateStudent`),
	updateTeacher = require(`./resolvers/mutation/updateTeacher`),
	updateSubject = require(`./resolvers/mutation/updateSubject`),
	updateClass = require(`./resolvers/mutation/updateClass`),
	addTeacher = require(`./resolvers/mutation/addTeacher`),
	addStudent = require(`./resolvers/mutation/addStudent`),
	addSubject = require(`./resolvers/mutation/addSubject`),
	createGist = require(`./resolvers/mutation/createGist`),
	addCourse = require(`./resolvers/mutation/addCourse`),
	addClass = require(`./resolvers/mutation/addClass`),
	login = require(`./resolvers/mutation/login`);

module.exports = {
	Query: {
		getGist,
		getClass,
		getCourses,
		getStudent,
		getTeacher,
		getAttendence,
		getDepartments,
		getFullMonthAttendence,
	},
	Mutation: {
		login,
		addClass,
		addCourse,
		addStudent,
		addSubject,
		addTeacher,
		createGist,
		updateClass,
		addAttendence,
		updateStudent,
		updateTeacher,
		updateSubject,
		updateAttendence,
		addAttendenceMany,
	},
};
